const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const moods=['😊 Happy','🥰 Loved','😌 Calm','😐 Normal','😔 Sad','😡 Angry','😰 Anxious','🤩 Excited','🥱 Tired','🥹 Emotional'];
const types=['Diary','Thought','Gratitude','Memory','Dream','Vent','Achievement','Goal','Reflection','Letter'];
const nav=[['MAIN','🏠 Home','📖 Diary','📅 Calendar','🖼️ Memories'],['DISCOVER','🕰️ Time Travel','📍 Memory Map','😊 Mood','🔎 Search My Life'],['PERSONAL','💌 Letters','🔒 Memory Capsules','🌙 Dreams','🏆 Milestones','📖 Yearbook'],['TOOLS','✨ Quick Capture','🤖 Ask My Diary','📝 Weekly Reflection'],['SETTINGS','🎨 Appearance','🔐 Privacy','⚙️ Settings']];
const seed=[{id:'1',title:'Today’s Entry',content:'Today I finally completed something I had been putting off for weeks. It felt like opening a window in a quiet room.',date:'2026-08-18T20:42:00Z',mood:'😊 Happy',type:'Diary',tags:['growth','home'],favorite:true,location:'Chandigarh',song:'Golden Hour — JVKE'},{id:'2',title:'A softer birthday',content:'I was nervous about starting, but everything changed in the best way. Look how far you have come.',date:'2025-08-18T19:16:00Z',mood:'🥹 Emotional',type:'Memory',tags:['birthday'],favorite:true,location:'Delhi'},{id:'3',title:'Strange quiet day',content:'Had a strange day, but I learned more about myself. Some feelings only make sense after writing them down.',date:'2026-08-17T19:16:00Z',mood:'😐 Normal',type:'Reflection',tags:['self'],favorite:false},{id:'4',title:'Independence Day walk',content:'Independence Day felt quieter than I expected. The evening sky looked like old paper.',date:'2026-08-15T21:05:00Z',mood:'😊 Happy',type:'Memory',tags:['walk'],favorite:false,location:'Delhi'}];
let profile=load('pp.profile',{name:'Srijan',diaryName:'Private Pages',passHash:'',theme:'Paper',accent:'#c65f3d',font:'Serif',sidebarCollapsed:false,autoLock:'5 minutes',aiConsent:false,onboarded:false});
let entries=load('pp.entries',seed), page='🏠 Home', locked=!!profile.passHash, draft=load('pp.draft','');
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}; function save(){localStorage.setItem('pp.profile',JSON.stringify(profile));localStorage.setItem('pp.entries',JSON.stringify(entries));document.documentElement.style.setProperty('--accent',profile.accent)}
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function render(){save(); if(!profile.onboarded)return onboarding(); if(locked)return lockScreen(); $('#app').innerHTML=`<button class="hamb" aria-label="Open menu">☰</button><aside class="side ${profile.sidebarCollapsed?'collapsed':''}">${sidebar()}</aside><main class="main ${profile.sidebarCollapsed?'wide':''}">${route()}</main><button class="fab" aria-label="Quick capture">+</button><div id="modal"></div>`; $('.hamb').onclick=()=>$('.side').classList.toggle('open'); $('.fab').onclick=quickCapture; wireNav();}
function onboarding(step=0){let code='', confirm=''; $('#app').innerHTML=`<section class="center"><div class="paper onboard"><div class="mark">🔐📖</div><div id="step"></div></div></section>`; const draw=()=>{$('#step').innerHTML= step===0?`<h1>Welcome to Private Pages.</h1><p>A private space that belongs only to you.</p><button class="btn">Create My Diary</button>`:step===1?form('What should your diary call you?',profile.name):step===2?form('Give your diary a name.',profile.diaryName,['Dear Diary','My Little World','Midnight Thoughts','Untold']):step===3?`<h1>Create your passcode.</h1><p>Use 4–6 digits. It is hashed locally before storage.</p><input id="code" type="password" inputmode="numeric" maxlength="6" placeholder="••••"><input id="confirm" type="password" inputmode="numeric" maxlength="6" placeholder="Confirm"><button class="btn">Continue</button>`:`<h1>Your private space is ready.</h1><p>Choose a readable theme, accent, font, diary style, and greeting.</p><select id="theme">${['Paper','Cream','Lavender','Sky','Forest','Sunset','Midnight','Minimal'].map(x=>`<option>${x}</option>`).join('')}</select><input id="accent" type="color" value="${profile.accent}"><select id="font"><option>Serif</option><option>Classic</option><option>Clean</option></select><button class="btn">Enter My Diary</button>`; $('.btn').onclick=async()=>{if(step===1){profile.name=$('input').value||'Friend'} if(step===2){profile.diaryName=$('input').value||'Private Pages'} if(step===3){code=$('#code').value;confirm=$('#confirm').value;if(code.length<4||code!==confirm)return alert('Passcodes must match and use 4–6 digits.')} if(step===4){profile.theme=$('#theme').value; profile.accent=$('#accent').value; profile.font=$('#font').value; profile.passHash=await hash(code||'1234'); profile.onboarded=true; locked=false; return render()} step++; draw()}; $$('.hint').forEach(b=>b.onclick=()=>{$('input').value=b.textContent})}; draw()}
function form(title,value,hints=[]){return `<h1>${title}</h1><input value="${value}">${hints.map(h=>`<button class="hint ghost">${h}</button>`).join('')}<button class="btn">Continue</button>`}
function lockScreen(){let pin=''; $('#app').innerHTML=`<section class="center"><div class="paper lock"><div class="mark">🔒</div><h1>${profile.diaryName}</h1><b>Your diary is locked.</b><p>Enter Passcode</p><div class="dots">${'<i></i>'.repeat(6)}</div><div class="keys">${'123456789'.split('').map(n=>`<button>${n}</button>`).join('')}<button data-clear>×</button><button>0</button><button data-back>⌫</button></div><button class="link">Use Biometrics</button><button class="link" id="hide">Quick Hide</button><p id="err" role="alert"></p></div></section>`; $$('.keys button').forEach(b=>b.onclick=async()=>{if(b.dataset.clear)pin='';else if(b.dataset.back)pin=pin.slice(0,-1);else pin=(pin+b.textContent).slice(0,6); $$('.dots i').forEach((d,i)=>d.classList.toggle('on',!!pin[i])); if(pin.length>=4&&await hash(pin)===profile.passHash){locked=false;render()} else if(pin.length===6){$('#err').textContent="That passcode isn't right."; $('.lock').classList.add('shake'); pin=''; setTimeout(()=>render(),550)}}); $('#hide').onclick=()=>location.href='about:blank'}
function sidebar(){return `<div class="brand"><span>📖</span><b>${profile.diaryName}</b><button id="collapse" aria-label="Collapse sidebar">‹</button></div><nav>${nav.map(([s,...items])=>`<p>${s}</p>${items.map(i=>`<button class="nav ${page===i?'active':''}" title="${i.slice(2)}" data-page="${i}"><span>${i.slice(0,2)}</span><b>${i.slice(2)}</b></button>`).join('')}`).join('')}</nav><button class="locknow">🔒 <b>Lock Diary</b></button>`}
function wireNav(){$$('.nav').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()}); $('#collapse').onclick=()=>{profile.sidebarCollapsed=!profile.sidebarCollapsed;render()}; $('.locknow').onclick=()=>{locked=true;render()}}
function route(){const key=page.slice(2); if(key==='Home')return home(); if(key==='Diary')return diary(); if(key==='Calendar')return calendar(); if(key==='Search My Life')return search(); if(key==='Privacy')return privacy(); if(key==='Appearance')return appearance(); return feature(key)}
function shell(t,s,c){return `<header><p class="kicker">Write. Capture. Remember. Rediscover.</p><h1>${t}</h1><p>${s}</p></header>${c}`}
function moodPicker(){return `<div class="moods">${moods.map(m=>`<button>${m}</button>`).join('')}<button>+ Custom</button></div>`}
function cards(items){return `<div class="cards">${items.map(([a,b])=>`<section class="paper"><p>${a}</p><b>${b}</b></section>`).join('')}</div>`}
function entry(e){if(!e)return empty('Your story starts here. Write your first memory.'); return `<article class="paper entry"><div><small>${new Date(e.date).toLocaleString()} · ${e.type}</small><button class="star" data-id="${e.id}">${e.favorite?'★':'☆'}</button><h2>${e.title}</h2></div><p>${e.extraPrivate?'🔐 Extra private entry — unlock again to preview.':e.content}</p><em>${e.mood} ${e.tags.map(t=>'#'+t).join(' ')} ${e.location?'📍 '+e.location:''} ${e.song?'🎵 '+e.song:''}</em></article>`}
function afterEntries(){$$('.star').forEach(b=>b.onclick=()=>{entries=entries.map(e=>e.id===b.dataset.id?{...e,favorite:!e.favorite}:e);render()})}
function home(){setTimeout(afterEntries); const month=new Set(entries.filter(e=>e.date.startsWith('2026-08')).map(e=>e.date.slice(0,10))).size; return shell(`Good evening, ${profile.name}.`,'How did today feel?',`${moodPicker()}<section class="paper prompt"><p>Today's Entry</p><button class="btn" onclick="window.goDiary()">+ Write Today's Entry</button><button class="ghost">✨ Capture a Memory</button></section>${cards([['Total memories',entries.length],['Days written this month',month],['Current streak','6 days'],['Longest streak','6 days']])}<h2>On This Day</h2>${entry(entries[1])}<h2>Recent Memories</h2>${entries.slice(0,3).map(entry).join('')}`)}
window.goDiary=()=>{page='📖 Diary';render()};
function diary(){setTimeout(()=>{const ta=$('#draft'); ta.oninput=()=>{draft=ta.value; $('#saveState').textContent=navigator.onLine?'Saved just now':'Saved locally'; clearTimeout(window.t); window.t=setTimeout(()=>localStorage.setItem('pp.draft',JSON.stringify(draft)),350)}; $('#saveEntry').onclick=()=>{if(!draft.trim())return; entries=[{id:crypto.randomUUID(),title:'Today’s Entry',content:draft,date:new Date().toISOString(),mood:'😌 Calm',type:$('#etype').value,tags:[],favorite:false},...entries]; draft=''; localStorage.removeItem('pp.draft');render()}}); return shell(`Today's Entry`,`${new Date().toLocaleDateString()} · <span id="saveState">Saved locally</span>`,`${moodPicker()}<section class="paper editor"><div class="toolbar"><b>B</b><i>I</i><u>U</u><b>H1</b><span>• List</span><span>” Quote</span><span>Align</span></div><textarea id="draft" placeholder="Dear diary, today...">${draft}</textarea><div class="toolbar"><select id="etype">${types.map(t=>`<option>${t}</option>`).join('')}</select><button>🏷️ Add tags</button><button>📷 Add photo</button><button>🎤 Voice</button><button>🎵 Song</button><button id="saveEntry" class="btn">Save privately</button></div></section>`)}
function calendar(){return shell('Calendar','Days with memories carry mood indicators; open a day to revisit entries.',`<section class="paper calendar">${Array.from({length:31},(_,i)=>{const d=i+1,e=entries.find(x=>new Date(x.date).getUTCDate()===d);return `<button><b>${d}</b><span>${e?e.mood.slice(0,2):''}</span></button>`}).join('')}</section>`)}
function search(){setTimeout(()=>{$('#q').oninput=render}); const q=$('#q')?.value||''; const r=entries.filter(e=>(e.content+e.title+e.tags.join(' ')+e.mood+e.type+e.location+e.song+e.date).toLowerCase().includes(q.toLowerCase())); setTimeout(afterEntries); return shell('Search My Life','Private local search across entry content, titles, tags, moods, dates, people, places, songs, and types.',`<input id="q" class="search" value="${q}" placeholder="college, happy memories, birthday, August 2025…">${r.map(entry).join('')||empty('Your story starts here. Write your first memory.')}`)}
function privacy(){setTimeout(()=>{$('#auto').onchange=e=>{profile.autoLock=e.target.value;render()};$('#ai').onchange=e=>{profile.aiConsent=e.target.checked;render()};$('#lockBtn').onclick=()=>{locked=true;render()}}); return shell('Privacy Center','Passcodes are hashed locally. Supabase Row Level Security policies are included for cloud isolation. AI is off by default and requires consent.',`${cards([['Auto-lock',profile.autoLock],['Biometrics','Use device support where available'],['AI access',profile.aiConsent?'On':'Off'],['Exports','Require authentication']])}<section class="paper settings"><label>Auto-lock <select id="auto">${['Immediately','1 minute','5 minutes','15 minutes','Never'].map(x=>`<option ${x===profile.autoLock?'selected':''}>${x}</option>`).join('')}</select></label><button id="lockBtn" class="btn">Lock Diary Now</button><label><input id="ai" type="checkbox" ${profile.aiConsent?'checked':''}> Allow Ask My Diary to process selected diary content with an external AI service</label><button class="ghost">Export Everything</button><button class="ghost">Delete all data…</button></section>`)}
function appearance(){setTimeout(()=>{$$('input,select').forEach(el=>el.onchange=()=>{profile.name=$('#name').value;profile.diaryName=$('#diaryName').value;profile.theme=$('#theme').value;profile.accent=$('#accent').value;render()})});return shell('Appearance','Themes, accent, font, diary name, greeting, card style, and background style stay readable.',`<section class="paper settings"><input id="name" value="${profile.name}"><input id="diaryName" value="${profile.diaryName}"><select id="theme">${['Paper','Cream','Lavender','Sky','Forest','Sunset','Midnight','Minimal'].map(x=>`<option ${x===profile.theme?'selected':''}>${x}</option>`).join('')}</select><input id="accent" type="color" value="${profile.accent}"></section>`)}
function feature(name){const copy={Memories:'A private photo and memory album for captions, diary entries, voice notes, songs, and locations.','Time Travel':'Open a random page from your old notebook.', 'Memory Map':'Optional location pins only appear when you approve locations.', Mood:'Mood calendar, distribution, monthly trend, most common mood, and journaling frequency are descriptive, not medical.', Letters:'Write letters to future you and keep them sealed until tomorrow, a birthday, or a custom date.','Memory Capsules':'Collect entries, photos, songs, thoughts, and voice notes; seal them until a future date.',Dreams:'Record dream titles, symbols, people, places, intensity, date, and mood.',Milestones:'A warm life timeline for graduations, first jobs, launches, trips, moves, and important memories.',Yearbook:'Generate a yearly collection of entries, photos, moods, streaks, milestones, places, songs, quotes, and reflections.','Quick Capture':'Choose write entry, photo, voice memory, quick thought, future letter, dream, or vent.','Ask My Diary':profile.aiConsent?'Ask consented questions over selected diary content.':'AI is off. Enable it in Privacy before any diary content is processed externally.','Weekly Reflection':'Save what went well, what was difficult, and what next week should look like.',Settings:'Profile, notification controls, PDF/Markdown/plain text/JSON export, backup, restore, and account actions.'}; setTimeout(afterEntries); return shell(name,copy[name]||'Your private space.',`${cards([['Connected state','Saved local diary data'],['Memories available',entries.length],['Favorites',entries.filter(e=>e.favorite).length],['Secure cloud path','Supabase schema ready']])}${name==='Time Travel'?entry(entries[Math.floor(Math.random()*entries.length)]):''}${name==='Mood'?moodPicker():''}${empty(name==='Memory Capsules'?'Some memories are worth saving for later.':name==='Letters'?'Write something for the future you.':'This corner is ready for your memories.')}`)}
function empty(text){return `<section class="paper empty"><b>✨</b><h2>${text}</h2></section>`}
function quickCapture(){$('#modal').innerHTML=`<div class="overlay"><section class="paper quick"><button id="close">×</button><h2>Quick Capture</h2>${['✍️ Write Entry','📸 Capture Photo','🎤 Voice Memory','💭 Quick Thought','💌 Future Letter','🌙 Dream','😤 Vent'].map(x=>`<button class="choice">${x}</button>`).join('')}</section></div>`; $('#close').onclick=()=>$('#modal').innerHTML=''; $$('.choice').forEach(b=>b.onclick=()=>{page=b.textContent.includes('Letter')?'💌 Letters':b.textContent.includes('Dream')?'🌙 Dreams':'📖 Diary';render()})}
render();
