create extension if not exists pgcrypto;
create table profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default 'Friend', diary_name text not null default 'Private Pages', passcode_hash text, created_at timestamptz default now());
create table entry_types (id bigserial primary key, name text unique not null, icon text not null);
create table moods (id bigserial primary key, user_id uuid references auth.users(id) on delete cascade, label text not null, emoji text not null, unique(user_id,label));
create table diary_entries (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, entry_type text not null default 'Diary', title text, content text not null default '', mood text, entry_date timestamptz not null default now(), favorite boolean default false, extra_private boolean default false, expires_at timestamptz, search tsvector generated always as (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(content,''))) stored, created_at timestamptz default now(), updated_at timestamptz default now());
create table tags (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, unique(user_id,name));
create table entry_tags (entry_id uuid references diary_entries(id) on delete cascade, tag_id uuid references tags(id) on delete cascade, primary key(entry_id,tag_id));
create table attachments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, entry_id uuid references diary_entries(id) on delete cascade, kind text check (kind in ('photo','audio','file')), storage_path text not null, caption text, created_at timestamptz default now());
create table songs (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, entry_id uuid references diary_entries(id) on delete cascade, title text not null, artist text, cover_path text, external_url text);
create table locations (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, entry_id uuid references diary_entries(id) on delete cascade, label text not null, lat numeric, lng numeric);
create table letters (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, title text, body text not null, unlock_at timestamptz not null, created_at timestamptz default now());
create table memory_capsules (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, title text not null, sealed_until timestamptz not null, created_at timestamptz default now());
create table capsule_items (id uuid primary key default gen_random_uuid(), capsule_id uuid references memory_capsules(id) on delete cascade, entry_id uuid references diary_entries(id) on delete cascade, attachment_id uuid references attachments(id) on delete cascade, note text);
create table dreams (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, title text not null, description text, people text[], places text[], symbols text[], mood text, intensity int check(intensity between 1 and 10), dream_date date default current_date);
create table milestones (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, title text not null, icon text, milestone_date date not null, description text);
create table weekly_reflections (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, week_start date not null, went_well text, difficult text, next_week text, entry_id uuid references diary_entries(id) on delete set null);
create table voice_entries (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, entry_id uuid references diary_entries(id) on delete cascade, audio_path text not null, transcript text);
create table yearbooks (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, year int not null, summary jsonb not null default '{}', pdf_path text, unique(user_id,year));
create table user_preferences (user_id uuid primary key references auth.users(id) on delete cascade, theme text default 'Paper', accent text default '#c65f3d', font text default 'Serif', sidebar_collapsed boolean default false, greeting text default 'Good evening');
create table privacy_settings (user_id uuid primary key references auth.users(id) on delete cascade, biometrics boolean default false, auto_lock text default '5 minutes', ai_access boolean default false, analytics boolean default false, cloud_backup boolean default true, notification_previews boolean default false, location_access boolean default false);
create index diary_entries_user_date_idx on diary_entries(user_id, entry_date desc);
create index diary_entries_search_idx on diary_entries using gin(search);
create index tags_user_name_idx on tags(user_id,name);
alter table profiles enable row level security; alter table moods enable row level security; alter table diary_entries enable row level security; alter table tags enable row level security; alter table entry_tags enable row level security; alter table attachments enable row level security; alter table songs enable row level security; alter table locations enable row level security; alter table letters enable row level security; alter table memory_capsules enable row level security; alter table capsule_items enable row level security; alter table dreams enable row level security; alter table milestones enable row level security; alter table weekly_reflections enable row level security; alter table voice_entries enable row level security; alter table yearbooks enable row level security; alter table user_preferences enable row level security; alter table privacy_settings enable row level security;
create policy own_profiles on profiles using (auth.uid()=id) with check (auth.uid()=id);
create policy own_entries on diary_entries using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_tags on tags using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_moods on moods using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_attachments on attachments using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_songs on songs using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_locations on locations using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_letters on letters using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_capsules on memory_capsules using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_dreams on dreams using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_milestones on milestones using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_weekly on weekly_reflections using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_voice on voice_entries using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_yearbooks on yearbooks using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_prefs on user_preferences using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_privacy on privacy_settings using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy own_entry_tags on entry_tags using (exists (select 1 from diary_entries e where e.id=entry_id and e.user_id=auth.uid())) with check (exists (select 1 from diary_entries e where e.id=entry_id and e.user_id=auth.uid()));
create policy own_capsule_items on capsule_items using (exists (select 1 from memory_capsules c where c.id=capsule_id and c.user_id=auth.uid())) with check (exists (select 1 from memory_capsules c where c.id=capsule_id and c.user_id=auth.uid()));
insert into entry_types(name,icon) values ('Diary','📖'),('Thought','💭'),('Gratitude','🙏'),('Memory','🖼️'),('Dream','🌙'),('Vent','😤'),('Achievement','🏆'),('Goal','🎯'),('Reflection','📝'),('Letter','💌') on conflict do nothing;
